# Generated by Django 6.0.1 on 2026-01-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newspaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "published_year",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("issue_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("content", models.TextField()),
                (
                    "language",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "English"), (2, "Uzbek")], default=2
                    ),
                ),
                ("published_year", models.DateField(default=None, null=True)),
                ("link", models.URLField(blank=True, default=None, null=True)),
                (
                    "newspaper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.newspaper",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_year", "newspaper"],
            },
        ),
    ]
