# Generated by Django 6.0.1 on 2026-01-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        # Alter columns to smallint while extracting year from existing dates
        migrations.RunSQL(
            sql=(
                "ALTER TABLE main_app_article "
                "ALTER COLUMN published_year TYPE smallint USING EXTRACT(YEAR FROM published_year)::smallint;"
            ),
            reverse_sql=(
                "ALTER TABLE main_app_article "
                "ALTER COLUMN published_year TYPE date USING TO_DATE(published_year::text || '-01-01', 'YYYY-MM-DD');"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE main_app_newspaper "
                "ALTER COLUMN published_year TYPE smallint USING EXTRACT(YEAR FROM published_year)::smallint;"
            ),
            reverse_sql=(
                "ALTER TABLE main_app_newspaper "
                "ALTER COLUMN published_year TYPE date USING TO_DATE(published_year::text || '-01-01', 'YYYY-MM-DD');"
            ),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
