# Generated by Django 4.2 on 2023-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "English"), (2, "Uzbek")], default=2
            ),
        ),
    ]
