# Generated by Django 4.2 on 2023-04-23 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_article_search_vector_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="main_app_ar_search__c144b8_gin",
        ),
        migrations.RemoveField(
            model_name="article",
            name="search_vector",
        ),
    ]
