# Generated by Django 4.2 on 2023-08-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_remove_article_main_app_ar_search__c144b8_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="issue_number",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="published_year",
            field=models.DateField(default=None, null=True),
        ),
    ]
