# Generated by Django 4.2 on 2023-08-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_article_issue_number_article_published_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
