# Generated by Django 4.2 on 2023-09-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_alter_article_author_alter_article_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_year", "newspaper"]},
        ),
        migrations.AddField(
            model_name="article",
            name="word_count_total",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="word_count_unique",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
